### ISSUE TITLE
[FEATURE] Support referencing modules via git urls

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#90] opened 2022-08-30 10:14 UTC
**Is your feature request related to a problem? Please describe.**
Multiple teams using seed-farmer as the deployment mechanism would require a way to reuse modules from each other across different git repositories. 

**Describe the solution you'd like**
Allow referencing modules via git urls including version/commit hash pegging. For example, see how terraform does this (https://www.terraform.io/language/modules/sources#github)

Allow specifying the module path as a git URL in the manifest:

```yaml
name: networking
path: git::https://example.com/network.git//modules/vpc?ref=v1.2.0
parameters:
  - name: internet-accessible
    value: true
---
name: buckets
path: modules/optionals/buckets
parameters:
  - name: encryption-type
    value: SSE
```

**Describe alternatives you've considered**
Git subtrees can be used to get around this, although it bloats the code and adds much more complexity.

**Comment by chamcca** [comment] 2022-09-27 21:16
# Proposal

rather than reusing the `path` attribute to reference either a local or git path, propose instead we add an optional `git` attribute to the Module Manifest
```
name: networking
path: git-modules/network/modules/vpc
git: 
  repository: https://example.com/network.git
  branch: v1.2.0
parameters:
  - name: internet-accessible
    value: true
```
on `seedfarmer apply` the bundling and deployment of modules will:
1. check the local, relative `path` for the module code, if directory exists and is not empty, bundle and deploy the module
2. if the local, relative `path` directory does not exist or is empty, peform a `git clone` of the `repository` into top-most directory referneced in `path` (in this example **git-modules**)
3. reattempt to locate the module code by checking the local, relative `path`. if the directory exists and is not empty, bundle and deploy, else ERR

utilizing this workflow has a few advantages:
- during module development the local, relative `path` will contain the module code being developed and tested. performing `seedfarmer apply` will utilize the local code
- cloning into the top most directory referenced in `path` (here **git-modules**) and locating modules within sub-directories enables the git repository to contain more than one module. the repository will be cloned once when the first module references the directory
- varying versions/branches of the same repository can be used for different modules by adjusting the top most directory, for example:
  ```
  name: networking
  path: git-modules-1/my-repo/modules/networking/vpc
  git: 
    repository: https://example.com/my-repo.git
    branch: v1.2.0
  parameters:
    - name: internet-accessible
      value: true
  ---
  name: buckets
  path: git-modules-2/my-repo/modules/buckets
  git: 
    repository: https://example.com/my-repo.git
    branch: v1.3.0
  parameters:
    - name: encryption-type
      value: SSE
  ```

**Comment by a13zen** [comment] 2022-09-28 08:26
Interesting approach. I can see the appeal for adding local development support, but just to challenge some assumptions 😅😅😅😅😅😅😅😅 :

- ***If we planned a module to be referenced via git, would that module not be developed in the referenced git repository directly?*** Why add the complexity of both local and remote support in one reference? As a developer, if I would like to develop locally in the same repo, I would just clone the module repo into the modules folder (as a git subtree) and work from that, changing the reference to be local instead of git. 

- ***Is the approach above truly code first & declarative?*** Since what gets deployed depends on what is available on a developer's local machine, there will be side effects which might be unexpected. Instead of declaring exactly what we expect to happen in the manifest, there is now branching logic built in so we can't be sure if what got deployed was something local or something remote. 

- ***The Terraform example above also supports having multiple modules in one git repo.*** The target module is specified using the double slash `//` notation followed by a path, for instance `git::https://example.com/network.git//modules/vpc?ref=v1.2.0` which would expect the repo to contain a modules folder at the root and then a vpc subfolder. 

```
- modules/
   | - vpc/
```

- ***Why tie modules together (version/branch etc.) to the topmost directory if they get deployed independently on CodeBuild?*** Doesn't this remove a lot of flexibility? Why not just allow each to have its own path, making things much simpler? It means more clone requests, but each clone could reference whichever tag/version/branch they'd like. 

What do you think?

**Comment by chamcca** [comment] 2022-09-28 13:34
unfortunately, due to the way deployment change sets, module roles, modulestack.yaml, and the deployspec.yaml are processed, all git referenced module code must be cloned locally to the CLI execution environment before being bundled and passed to CodeBuild. we are unable to simply clone the repository during CodeBuild execution. the proposal was an attempt at optimizing the CLI performance and module builder experience. though I agree it adds some complexity and ambiguity.

because we need to clone locally, a local path to clone into is required. we can either reuse the `path` attribute to determine where to clone into, or hide the cloned repository in the codeseeder.out/ directory. without a mechanism to declare and reuse the path to clone into, the CLI will have to locally clone the entire repo for each module. cloning would need to occur immediately so that we can dynamically determine which modules need to be deployed, this also includes a `--dry-run`. using the top most directory of the path was an attempt at reducing the number clone operations and cleanups locally. i suppose we could reduce this impact by limiting (or enabling restriction of) the cloning depth to 1.

from a module development perspective I was trying to reduce the round trips on the development cycle. if we don't enable an option to test deployment of a module from local source, then all changes must be added, committed, and pushed remotely before any integration/regression testing can occur. but I can see what you mean about changing the way development is done and doing a clone of the repo into the modules folder or another **git-modules** folder.

**Comment by chamcca** [comment] 2022-09-28 14:19
it might be possible to cache checkouts/clones per repository/ref in our codeseeder.out/ directory enabling some reuse of optimization. with that and shifting how i was thinking about the builder workflow, i think you've convinced me.

**Closed** 2022-09-29 14:22 UTC
Labels: enhancement
