### ISSUE TITLE
[BUG] Seedfarmer loads user parameter when resolving manifiests

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#420] opened 2023-09-20 08:19 UTC
**Describe the bug**
While deploying database, I have added a ssm parameter with name of the secret:
```
# SSM param with secret ARN\
self.cluster_secret_arn_ssm_param = ssm.StringParameter(
    self,
   "secret-ssm-param",
    parameter_name=f"/addf/{deployment_name}/{module_name}/{database_name}/secret-arn",
    string_value=self.cluster.secret.secret_arn,
)
```
**This parameter was not used in any manifest**

In subsequent run, SeedFarmer was failing with json decode issues. After debugging source code, it turns out it was failing on decoding the value of this parameter. 
From initial inspection, it seems to me that seedfarmer loads all parameters starting with "/addf/{deployment_name}/{module_name}/ instead of only the ones it uses.

**To Reproduce**
1. Create module that creates ssm parameter prefixed /addf/{deployment_name}/{module_name}/
2. Deploy the module
3. Do some changes and try to deploy module again

**Expected behavior**
Seedfarmer loads only seedfarmer parameters

**Comment by dgraeber** [comment] 2023-09-20 13:28
This is correct.  Seed-Farmer loads all parameters associated with the deployment as designated by the naming convention `/addf/{deployment_name}/{module_name}/`.  Seed-Farmer fetches all SSM parameters with this naming convention prior to deploying.  This is due to the distributed nature that seed-farmer supports (multi-account / multi-region).  We consider SSM parameters with this naming pattern to be for seed-farmer (consider it to be reserved).

There is no way for Seed-Farmer (in distributed fashion) to know what ssm parameter with this naming convention is NOT for seed-farmer (or tied to a specific module).

This is by design.

**Comment by zaremb** [comment] 2023-09-20 13:37
I was not aware that that was by design. I thought there is only specific list of ssm parameters that seedfarmer produces:
`/addf/{deployment_name}/{module_name}/` + `deployspec OR manifest OR metadata OR /md5/deployspec OR /md5/manifest`. If that would be the case, id expect to restrict to seedfarmer to read only those params.

For me, the location `/addf/{deployment_name}/{module_name}/` is a natural place to put module specific ssm parameters as well. Can you please include the information that this namespace is reserved? 

Another ask: In case issue like this happens, so json loads fails, could you print the name of the parameter that json loads failed for? It would help with debugging a lot.

**Comment by dgraeber** [comment] 2023-09-21 16:37
@zaremb I think we can filter on the 6 reserved parameter names needed by seed-farmer (`["deployspec", "bundle","metadata","md5","manifest","deployed"]` ).   Lets talk to confirm...

**Comment by dgraeber** [comment] 2023-09-21 17:00
@zaremb after reviewing this, rather than filter on the reserved words, perhaps we can just alleviate the decode issue...can explain when we talk

**Comment by dgraeber** [comment] 2023-09-22 17:14
Will be in next patch release

**Closed by dgraeber** 2023-09-22 17:14 UTC
Labels: bug
