### ISSUE TITLE
[BUG] Seedfarmer 4.0.4 doesn't actually delete the modules if they were deleted from manifests

### ISSUE THREAD

**Issue by ktulhax** [awslabs/seed-farmer#719] opened 2024-09-10 09:07 UTC
**Describe the bug**

Seedfarmer successfully finish seedfarmer apply in case if the module was deleted from .yaml manifest or/and the folder with this module was also deleted, but it doesn't actually delete resources, i.e.:
- it deletes cached code from bucket
- it deletes entries from SSM parameters storage
- BUT it doesn't delete the CloudFormation stacks and relevant resources

**To Reproduce**
1. Have a project with two modules which are referencing to different folders
2. Create inital deployment with `seedfarmer apply`
3. Delete one of the module from manifest and delete the folder with this module as well
4. Do `seedfarmer apply` again
5. See the result described above

**Expected behavior**
It was expected that after `seedfarmer apply` all relevant resouces will be deleted

**Additional context**
The testing has been done for StepFunction and LogGroup modules

**Comment by dgraeber** [comment] 2024-09-10 13:10
@ktulhax Thanks for this issue.  The only resources SF creates are the seedkit (for the entire project via CodeSeeder), the module role (with an attached modulestack if defined) and leverages SSM (no resources there).  All other resources are created and destroy by the module.

In your case, you successfully deleted the cached bundle and the SSM metadata for the module (indicating that the module reported back that the destroy was successful).  The only remaining resource that SF is aware of this the module role. 

Can you provide more info regarding the CFN stack that persists?  The name will indicate the usage .  Also provide any other pertinent info (the module you are using .... a sample manifest with no proprietary info, etc).  We will investigate your use case.

**Comment by dgraeber** [comment] 2024-10-16 02:00
Closing due to lack of info / inability to reproduce

**Closed by dgraeber** 2024-10-16 02:00 UTC
Labels: bug
