### ISSUE TITLE
[BUG] Seedfarmer fails to destroy modules when deployed in VPC

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#391] opened 2023-07-21 09:16 UTC
**Describe the bug**
I have a codeseeder project  within VPC. When I try to destroy modules, some were destroyed but now the destroy process is stuck, as codeseeder codebuild project is stuck at QUEUED phase error: UNAUTHORIZED_OPERATION_DELETE_NETWORK_INTERFACE: The service role is not authorized to perform ec2:DeleteNetworkInterface 

**To Reproduce**
1. Deploy modules from codeseeder in VPC
2. Start destroying modules in VPC
3. See error
<img width="1177" alt="image" src="https://github.com/awslabs/seed-farmer/assets/18630245/a09b92d1-dedf-421e-ba4a-2ccb39a7dbb2">

**Expected behavior**
Codeseeder codebuild project should not fail when destroying modules when running inside VPC

**Additional context**
Required permissions to deploy in VPC: https://docs.aws.amazon.com/codebuild/latest/userguide/auth-and-access-control-iam-identity-based-access-control.html#customer-managed-policies-example-create-vpc-network-interface

**Comment by dgraeber** [comment] 2023-07-21 11:23
Can you give some more information so we can try and replicate?  Is this during `seedfarmer destroy` invocation or after you removed modules from the manifest and invoked `seedfarmer apply`?  You mentioned `some were destroyed but now the destroy process is stuck` - does this mean that SOME modules destroyed and some did not?  What were the modules that were successfully destroyed and not?  Did some fail to destroy? 

The seedkit is not managed by a codebuild job - what is that screenshot from?  Is that a module?  At what point in the process did you get there?  The steps you indicated above have been followed previously and we did not encounter this issue, so we are trying to fully understand how to replicate.

**Comment by zaremb** [comment] 2023-07-21 14:32
Sure. 
- Is this during seedfarmer destroy invocation or after you removed modules from the manifest and invoked seedfarmer apply? Its seedfarmer destroy command
-  You mentioned some were destroyed but now the destroy process is stuck - does this mean that SOME modules destroyed and some did not? Yes, about half of the modules were successfully destroyed.
- What were the modules that were successfully destroyed and not? There is a lot of them, but for example EKS module was destroyed but replication module cannot be destroyed due to the error.
-  Did some fail to destroy? No, all succeeded.
- The screenshot is from the codebuild project called "codeseeder-addf", its the one that deployes the modules. Screenshot is from the codebuild job that was trying to run destroy of replication

**Comment by dgraeber** [comment] 2023-08-01 05:10
Hi - the `seedfarmer apply` and `seedfarmer destroy` cli does not operate within a codebuild project.  You may be invoking the seedfarmer cli from a codebuild project (and that invocation is done via the codebuild service role) but that is outside of the scope of seedfarmer and the deployment roles.  

So there are two scenarios where creating / removing a ENI can occur:
1. as part of a module -- in which any problem that occurs lies with the module itself and not seedfarmer
2. when creating / destroying the seedkit (via codeseeder api in seedfarmer) - in this scenario, a seedfarmer deployment role (for an account/region mapping) has the permissions to create a codebuild project with VPC support.  SeedFarmer does not destroy the seedkit on a `seedfarmer destroy` invocation and thus will not cause an error due to lack of destroy ENI permissions

**Comment by zaremb** [comment] 2023-08-01 07:13
None of the modules directly create/destroy the ENI. The command seedfarmer destroy was run on my machine and the error is in CodeBuild job managed by seedfarmer/codeseeder at QUEUEUD phase. I do not see how this could be a module problem. I can add delete ENI permissions to modulestack and that probably will work but **create ENI permission is added by default** (and delete is missing).

**Comment by dgraeber** [comment] 2023-08-21 14:44
Closing this issue as the root cause cannot be linked to SeedFarmer...we can reopen once further details are gathered.

**Closed by dgraeber** 2023-08-21 14:44 UTC
Labels: bug
